### ISSUE TITLE
Nuxt 2 start error - possible @nuxt/kit regression 

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-modules/tailwindcss#507]
### Version
@nuxtjs/tailwindcss: 5.3.0
nuxt: 2.15.8

### Reproduction Link

https://stackblitz.com/edit/nuxt-starter-zcq9qt?file=nuxt.config.js,package.json, see: https://github.com/nuxt-community/tailwindcss-module/issues/500

### Steps to reproduce

Add module, run dev.

It can be resolved by disabling the viewer:

```
tailwindcss: {
    viewer: false,
  },
```

### What is Expected?

It to work

### What is actually happening?

It crashes

```
 FATAL  Cannot read properties of undefined (reading 'push')                                                                                                                                    14:01:12

  at addDevServerHandler (node_modules/@nuxt/kit/dist/index.mjs:196:38)
  at setup (node_modules/@nuxtjs/tailwindcss/dist/module.mjs:199:7)
  at async ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:607:5)
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)
```

**Comment by harlan-zw** [comment]
Related @nuxt/kit PR: https://github.com/nuxt/framework/pull/4850/files
