### ISSUE TITLE
`postcss-custom-properties` is not being bundled

### ISSUE THREAD

**Issue by AnoRebel** [nuxt-modules/tailwindcss#576]
### Version
@nuxtjs/tailwindcss: 6.1.3
nuxt: 3.0.0 (Stable)

### Steps to reproduce
- Simply install the plugin and run the app

### What is Expected?
A working tailwind in the project

### What is actually happening?
```sh
 ERROR  Cannot start nuxt:  Cannot find module 'postcss-custom-properties'                         16:08:15
Require stack:
- /home/dev/Documents/Code/michapio/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:243302)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:260:29)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:280:24)
  at node_modules/@nuxt/vite-builder/dist/shared/vite-builder.1c88b3ee.mjs:670:20
  at Array.map (<anonymous>)
  at resolveCSSOptions (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.1c88b3ee.mjs:669:167)
  at bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.1c88b3ee.mjs:776:14)
```

### Fix
- Installing `postcss-custom-properties` manually seems to fix the issue

**Comment by mrnasil** [comment]
Any update?

**Comment by AnoRebel** [comment]
> Any update?

So far, I'm using the manual fix I wrote.

**Comment by mrnasil** [comment]
> 

How to fix this?

**Comment by ineshbose** [comment]
Seems to be fixed! Is this still being experienced?

**Comment by redakzter01** [comment]
> Seems to be fixed! Is this still being experienced?

One here, nuxt 3.8.2. Went good with the manual fix.
