### ISSUE TITLE
Can't use this plugin with nuxt3.1

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-modules/tailwindcss#586]
### Version
@nuxtjs/tailwindcss: 0.5.8
nuxt: Nuxt 3.0.1-rc.0-27863365.da6fa9a

### Steps to reproduce

Install this module in a nuxt3.1 project
Add a plugin in the `tailwind.config.js`

### What is Expected?

To work!

### What is actually happening?

This happens:

```
ERROR  Cannot start nuxt:  Cannot find module 'tailwindcss/plugin'                                                                         21:21:36
Require stack:
- C:\Users\esoubiran\projects\le-classement.fr\node_modules\@tailwindcss\typography\src\index.js

  Require stack:
  - node_modules\@tailwindcss\typography\src\index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
  at Function.resolve (node:internal/modules/cjs/helpers:109:19)
  at _resolve (node_modules\jiti\dist\jiti.js:1:243302)
  at jiti (node_modules\jiti\dist\jiti.js:1:245428)
  at C:/Users/esoubiran/projects/le-classement.fr/node_modules/@tailwindcss/typography/src/index.js:1:91
  at jiti (node_modules\jiti\dist\jiti.js:1:247502)
  at C:/Users/esoubiran/projects/le-classement.fr/nuxt.config.ts:1:204
  at Object.jiti (node_modules\jiti\dist\jiti.js:1:247502)
  at resolveConfig (/C:/Users/esoubiran/projects/le-classement.fr/node_modules/c12/dist/index.mjs:222:24)
  at loadConfig (/C:/Users/esoubiran/projects/le-classement.fr/node_modules/c12/dist/index.mjs:105:40)                                      21:21:34  
  at async loadNuxtConfig (/C:/Users/esoubiran/projects/le-classement.fr/node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:448:18)
  at async loadNuxt (/C:/Users/esoubiran/projects/le-classement.fr/node_modules/nuxt/dist/index.mjs:1856:19)
  at async loadNuxt (/C:/Users/esoubiran/projects/le-classement.fr/node_modules/@nuxt/kit/dist/index.mjs:493:19)
  at async load (/C:/Users/esoubiran/projects/le-classement.fr/node_modules/nuxi/dist/chunks/dev.mjs:6769:23)
  at async Object.invoke (/C:/Users/esoubiran/projects/le-classement.fr/node_modules/nuxi/dist/chunks/dev.mjs:6841:5)
  at async _main (/C:/Users/esoubiran/projects/le-classement.fr/node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by ineshbose** [comment]
Has this been resolved yet? @Barbapapazes
