### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'DEBUG')

### ISSUE THREAD

**Issue by NisuSan** [nuxt-modules/tailwindcss#653]
### Version
@nuxtjs/tailwindcss: v6.6.5 
nuxt: >v3.3.1

### Steps to reproduce
Just run the project

### What is Expected?
No error in the console :)

### What is actually happening?
In the browser console we got the error
```Uncaught TypeError: Cannot read properties of undefined (reading 'DEBUG')
    at node_modules/.pnpm/tailwindcss@3.3.1_postcss@8.4.21_ts-node@10.9.1/node_modules/tailwindcss/lib/lib/sharedState.js (sharedState.js:30:37)
    at __require (chunk-4EOJPDL2.js?v=83bc6954:8:50)
    at node_modules/.pnpm/tailwindcss@3.3.1_postcss@8.4.21_ts-node@10.9.1/node_modules/tailwindcss/lib/featureFlags.js (featureFlags.js:18:22)
    at __require (chunk-4EOJPDL2.js?v=83bc6954:8:50)
    at node_modules/.pnpm/tailwindcss@3.3.1_postcss@8.4.21_ts-node@10.9.1/node_modules/tailwindcss/lib/util/normalizeConfig.js (normalizeConfig.js:9:23)
    at __require (chunk-4EOJPDL2.js?v=83bc6954:8:50)
    at node_modules/.pnpm/tailwindcss@3.3.1_postcss@8.4.21_ts-node@10.9.1/node_modules/tailwindcss/lib/util/resolveConfig.js (resolveConfig.js:15:26)
    at __require (chunk-4EOJPDL2.js?v=83bc6954:8:50)
    at node_modules/.pnpm/tailwindcss@3.3.1_postcss@8.4.21_ts-node@10.9.1/node_modules/tailwindcss/lib/public/resolve-config.js (resolve-config.js:9:61)
    at __require (chunk-4EOJPDL2.js?v=83bc6954:8:50)```

**Comment by nickolson** [comment]
Looks like this might be related to this Tailwind issue (https://github.com/tailwindlabs/tailwindcss/issues/10918) and possibly fixed once the Tailwind dep gets updated to 3.3.1
