### ISSUE TITLE
Cannot find module '/home/runner/work/dashboard/dashboard/.nuxt/tailwind.config.cjs'

### ISSUE THREAD

**Issue by sawa-ko** [nuxt-modules/tailwindcss#683]
### Version
@nuxtjs/tailwindcss:  6.7.0
nuxt:  3.5.0
tailwindcss: 3.3.2

### Steps to reproduce

1. Create a nuxt project with latest stable version
2. See error

### What is Expected?
No error about the file mentioning the error not being found.

### What is actually happening?
I am currently getting an error that the tailwindcss.config.cjs file was not found. This problem happens to me both in github workflows, vercel, etc.

I have my `tailwind.config.ts` file in the root path of my project, in it I have all the configuration I use tailwindcss and I import the plugins `@tailwindcss/aspect-ratio`, `@tailwindcss/forms`, `@tailwindcss/typography`.

### Full Error
```
[log] Nuxi 3.5.0
[info] Using html-validate to validate server-rendered HTML
[info] [nuxt:tailwindcss] Using default Tailwind CSS file
[warn] [@nuxtjs/i18n] Vue I18n configuration file does not exist at i18n.config. Skipping...
[warn] [@nuxtjs/i18n] `i18n:extend-messages` is deprecated. That hook will be removed feature at the time of the v8 official release.
If you're using it, please use `i18n:registerModule` instead.
[info] [nuxt-auth] `nuxt-auth` setup starting
[success] [nuxt-auth] `nuxt-auth` setup done
Error:  ✖ Error while formatting the output 
Error: Cannot find module '/home/runner/work/dashboard/dashboard/.nuxt/tailwind.config.cjs'
Require stack:
- /home/runner/work/dashboard/dashboard/node_modules/.pnpm/tailwindcss@3.3.2_ts-node@10.9.1/node_modules/tailwindcss/lib/lib/load-config.js
Error:  Cannot find module '/home/runner/work/dashboard/dashboard/.nuxt/tailwind.config.cjs'
Require stack:
- /home/runner/work/dashboard/dashboard/node_modules/.pnpm/tailwindcss@3.3.2_ts-node@10.9.1/node_modules/tailwindcss/lib/lib/load-config.js
  Require stack:
  - node_modules/.pnpm/tailwindcss@3.3.2_ts-node@10.9.1/node_modules/tailwindcss/lib/lib/load-config.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
  at Function.resolve (node:internal/modules/cjs/helpers:116:19)
  at _resolve (node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/dist/jiti.js:1:241025)
  at jiti (node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/dist/jiti.js:1:243309)
  at node_modules/.pnpm/tailwindcss@3.3.2_ts-node@10.9.1/node_modules/tailwindcss/lib/lib/load-config.js:37:30
  at loadConfig (node_modules/.pnpm/tailwindcss@3.3.2_ts-node@10.9.1/node_modules/tailwindcss/lib/lib/load-config.js:39:6)
  at Bz (node_modules/.pnpm/prettier-plugin-tailwindcss@0.3.0_prettier@2.8.8/node_modules/prettier-plugin-tailwindcss/dist/index.js:2368:40744)
  at dI (node_modules/.pnpm/prettier-plugin-tailwindcss@0.3.0_prettier@2.8.8/node_modules/prettier-plugin-tailwindcss/dist/index.js:2368:40028)
  at Object.parse (node_modules/.pnpm/prettier-plugin-tailwindcss@0.3.0_prettier@2.8.8/node_modules/prettier-plugin-tailwindcss/dist/index.js:2368:43728)
  at Object.parse (node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:7515:23)
  at coreFormat (node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:[88](https://github.com/naeko-team/dashboard/actions/runs/5025463711/jobs/9012467241#step:7:89)29:18)
  at formatWithCursor2 (node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:[90](https://github.com/naeko-team/dashboard/actions/runs/5025463711/jobs/9012467241#step:7:91)21:18)
  at node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38183:12
  at format (node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38197:12)
  at formatOutputWithPrettier (node_modules/.pnpm/nuxt-typed-router@3.2.2/node_modules/nuxt-typed-router/dist/module.mjs:1255:30)
  at async processPathAndWriteFile (node_modules/.pnpm/nuxt-typed-router@3.2.2/node_modules/nuxt-typed-router/dist/module.mjs:1277:29)
  at async Promise.all (index 0)
  at async saveGeneratedFiles (node_modules/.pnpm/nuxt-typed-router@3.2.2/node_modules/nuxt-typed-router/dist/module.mjs:1367:3)
  at async node_modules/.pnpm/nuxt-typed-router@3.2.2/node_modules/nuxt-typed-router/dist/module.mjs:15[91](https://github.com/naeko-team/dashboard/actions/runs/5025463711/jobs/9012467241#step:7:92):7
  at async Object.getContents (node_modules/.pnpm/nuxt@3.5.0_@types+node@20.1.7_eslint@8.40.0/node_modules/nuxt/dist/index.mjs:649:9)
  at async node_modules/.pnpm/nuxt@3.5.0_@types+node@20.1.7_eslint@8.40.0/node_modules/nuxt/dist/index.mjs:3258:22
  at async Promise.all (index 30)
  at async generateApp (node_modules/.pnpm/nuxt@3.5.0_@types+node@20.1.7_eslint@8.40.0/node_modules/nuxt/dist/index.mjs:3257:3)
  at async _applyPromised (node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:54:10)
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by ineshbose** [comment]
@ploca14 it shouldn't be an issue in the latest version of the module. If it is, would you be able to provide a reproduction over Stackblitz please?

**Comment by ploca14** [comment]
Oh, I found that its caused by my prettier config
```
module.exports = {
  plugins: [require('prettier-plugin-tailwindcss')],
  tailwindConfig: '.nuxt/tailwind.config.cjs',
}
```

Should I point the tailwindConfig to the tailwind.config.ts file in the root of my project?

**Comment by ploca14** [comment]
> Oh, I found that its caused by my prettier config
> 
> ```
> module.exports = {
>   plugins: [require('prettier-plugin-tailwindcss')],
>   tailwindConfig: '.nuxt/tailwind.config.cjs',
> }
> ```
> 
> Should I point the tailwindConfig to the tailwind.config.ts file in the root of my project?

Nevermind, I see in the prettier plugin docs that the tailwindConfig property is not needed if the configs are in the same directory.
