### ISSUE TITLE
Build error after upgrade to `6.12.2` from `6.12.1`

### ISSUE THREAD

**Issue by HADB** [nuxt-modules/tailwindcss#909]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.16.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.12.2
- Builder:          -
- User Config:      compatibilityDate, devtools, eslint, routeRules, nitro, css, site, modules, content, icon, colorMode, plausible, robots, sitemap, tailwindcss, sentry, gtag
- Runtime Modules:  @nuxt/content@2.13.4, @nuxt/eslint@0.6.0, @nuxt/icon@1.5.6, @nuxt/image@1.8.1, @nuxt/ui@2.18.7, @nuxtjs/color-mode@3.5.1, @nuxtjs/plausible@1.0.3, @nuxtjs/robots@4.1.9, @nuxtjs/sitemap@6.1.2, @nuxtjs/tailwindcss@6.12.2, @sentry/nuxt/module@8.34.0, nuxt-gtag@3.0.1
- Build Modules:    -
------------------------------

### Describe the bug

Build error after upgrade to `6.12.2` from `6.12.1`

```
hadb.me git:(renovate/all-minor-patch) pnpm i
Lockfile is up to date, resolution step is skipped
Already up to date

> @ prepare /Users/bean/Projects/GitHub/HADB/hadb.me
> nuxt prepare

ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                      nuxt:tailwindcss 11:15:26

[11:15:27]  WARN  Duplicated imports "useTrackEvent", the one from "/Users/bean/Projects/GitHub/HADB/hadb.me/node_modules/.pnpm/@nuxtjs+plausible@1.0.3_magicast@0.3.5_rollup@4.21.0_webpack-sources@3.2.3/node_modules/@nuxtjs/plausible/dist/runtime/composables/useTrackEvent" has been ignored and "/Users/bean/Projects/GitHub/HADB/hadb.me/node_modules/.pnpm/nuxt-gtag@3.0.1_magicast@0.3.5_rollup@4.21.0_webpack-sources@3.2.3/node_modules/nuxt-gtag/dist/runtime/composables/useTrackEvent" is used


 ERROR  Cannot destructure property 'theme' of 'undefined' as it is undefined.                                             11:15:27

  at typography (tailwind.config.ts:32:22)
  at node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.21.0_webpack-sources@3.2.3/node_modules/@nuxtjs/tailwindcss/dist/module.mjs:135:18
  at _defu (node_modules/.pnpm/defu@6.1.4/node_modules/defu/dist/defu.mjs:31:19)
  at _defu (node_modules/.pnpm/defu@6.1.4/node_modules/defu/dist/defu.mjs:37:21)
  at _defu (node_modules/.pnpm/defu@6.1.4/node_modules/defu/dist/defu.mjs:37:21)
  at node_modules/.pnpm/defu@6.1.4/node_modules/defu/dist/defu.mjs:52:33
  at Array.reduce (<anonymous>)
  at node_modules/.pnpm/defu@6.1.4/node_modules/defu/dist/defu.mjs:52:16
  at configMerger (node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.21.0_webpack-sources@3.2.3/node_modules/@nuxtjs/tailwindcss/dist/module.mjs:138:5)
  at configs.reduce.configMerger.content.files (node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.21.0_webpack-sources@3.2.3/node_modules/@nuxtjs/tailwindcss/dist/module.mjs:249:23) 



 ERROR  Cannot destructure property 'theme' of 'undefined' as it is undefined.                                             11:15:27

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by HADB** [comment]
My `nuxt.config.ts`:

```ts
...
  tailwindcss: {
    cssPath: ['~/assets/css/tailwind.css', { injectPosition: 'last' }],
    configPath: 'tailwind.config.ts',
  },
...
```

I found that everything goes well if I remove `configPath: 'tailwind.config.ts',` from `nuxt.config.ts`.

Maybe there are some breaking changes for this redundant config.

**Comment by ineshbose** [comment]
Thanks for raising this. I see the repository on your profile, and I'll try to investigate further.

You don't need to provide configPath if it is already tailwind.config (and maybe the path resolution behaves odd without path specifier eg relative or project dir root). Still, it shouldn't cause issues between versions.

From the traceback, I'm thinking if it's this line - https://github.com/nuxt-modules/tailwindcss/blob/main/src/runtime/merger.js#L34

Again, this wasn't changed between 6.12.1 and 6.12.2 but I notice that the if condition rather belongs in the earlier block (how did we miss that 😄). Let me continue investigating

**Comment by letoast** [comment]
> Thanks for raising this. I see the repository on your profile, and I'll try to investigate further.
> 
> You don't need to provide configPath if it is already tailwind.config (and maybe the path resolution behaves odd without path specifier eg relative or project dir root). Still, it shouldn't cause issues between versions.
> 
> From the traceback, I'm thinking if it's this line - https://github.com/nuxt-modules/tailwindcss/blob/main/src/runtime/merger.js#L34
> 
> Again, this wasn't changed between 6.12.1 and 6.12.2 but I notice that the if condition rather belongs in the earlier block (how did we miss that 😄). Let me continue investigating

Hey, @ineshbose any update on this? We've upgraded nuxt/ui which depends on @nuxtjs/tailwindcss and now we have to lock the version of tailwindcss via resolutions.

**Comment by ineshbose** [comment]
It's possible that #913 could address this as it is changing config-loading strategy. Once merged, I shall be asking for feedback!

**Comment by ineshbose** [comment]
Merged! Could you give `nightly` a try and let me know how it goes please?

https://tailwindcss.nuxtjs.org/getting-started/installation#opting-into-the-nightly-channel

**Comment by ineshbose** [comment]
Hey @HADB @letoast would you be able to test and provide feedback if the issue has been fixed please?

**Comment by HADB** [comment]
@ineshbose I ran into another error with the nightly version:

```
 ERROR  x Build failed in 3.09s                                                                                                   10:32:57


[10:32:57]  ERROR  Nuxt Build Error: [vite:load-fallback] Could not load /Users/bean/Projects/GitHub/HADB/hadb.me/.nuxt/tailwind.config/theme/colors (imported by node_modules/.pnpm/@nuxt+ui@2.18.7_magicast@0.3.5_rollup@4.21.0_vite@5.4.7_@types+node@22.0.0_sass@1.80.4_terser_ex2undgjgyscydumoact7e7atu/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js): ENOENT: no such file or directory, open '/Users/bean/Projects/GitHub/HADB/hadb.me/.nuxt/tailwind.config/theme/colors'

  at async open (node:internal/fs/promises:638:25)
  at async Object.readFile (node:internal/fs/promises:1238:14)
  at async Object.load (node_modules/.pnpm/vite@5.4.7_@types+node@22.0.0_sass@1.80.4_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:65033:25)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:19813:28)
  at async node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:18977:33
  at async Queue.work (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20023:32)
```

**Comment by ineshbose** [comment]
> [@ineshbose](https://github.com/ineshbose) I ran into another error with the nightly version:
> 
> ```
>  ERROR  x Build failed in 3.09s                                                                                                   10:32:57
> 
> 
> [10:32:57]  ERROR  Nuxt Build Error: [vite:load-fallback] Could not load /Users/bean/Projects/GitHub/HADB/hadb.me/.nuxt/tailwind.config/theme/colors (imported by node_modules/.pnpm/@nuxt+ui@2.18.7_magicast@0.3.5_rollup@4.21.0_vite@5.4.7_@types+node@22.0.0_sass@1.80.4_terser_ex2undgjgyscydumoact7e7atu/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js): ENOENT: no such file or directory, open '/Users/bean/Projects/GitHub/HADB/hadb.me/.nuxt/tailwind.config/theme/colors'
> 
>   at async open (node:internal/fs/promises:638:25)
>   at async Object.readFile (node:internal/fs/promises:1238:14)
>   at async Object.load (node_modules/.pnpm/vite@5.4.7_@types+node@22.0.0_sass@1.80.4_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:65033:25)
>   at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:19813:28)
>   at async node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:18977:33
>   at async Queue.work (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20023:32)
> ```

I'm trying to reproduce this on your repository, but not able to hit it - could you point me how to cause this error?

**Comment by ineshbose** [comment]
Should be resolved on nightly now! Let me know. Will reopen if issues persists.
