### ISSUE TITLE
Changes in Tailwind CSS v4

### ISSUE THREAD

**Issue by ineshbose** [nuxt-modules/tailwindcss#919]
Hi everyone,

I'm creating this issue to get an idea from the users of this module about certain changes and features in Tailwind CSS v4 that they'd like this module to integrate with.

If you haven't already, do give a read to the v4 prerelease documentation that covers all the changes:
https://tailwindcss.com/docs/v4-beta

I mention in #790 that this module mostly aims at installing and configuring Tailwind to your Nuxt project a breeze, and with this new version, Tailwind CSS has made it even easier; still, there are minor steps like configuring Vite within Nuxt (or webpack/other builders using PostCSS), setting up CSS, merging all the Nuxt layers, etc -- this is where the module would still be required.

There are a few more things that have changed in Tailwind CSS v4 that heavily influence on the approach for the next version of this module; I'm hoping to get comments on these functionalities (and more general bits I may have missed).

## Configuration

Previously Tailwind required us to create a `tailwind.config.js` to enable minimum installation; this configuration file also helps in using plugins, safelists, and extending theme. This is no longer necessary, you can use v4 without a configuration file.

How would you configure the theme?

The idea of Tailwind v4 is that it will be more `tailwind.css` configuration focused, than `tailwind.config.cjs` (based on my understanding from [this video](https://www.youtube.com/watch?v=vhcntygYBsI)). So, you have the `@theme` directive. Read more about this here - https://tailwindcss.com/docs/v4-beta#customizing-your-theme

With that said, any (existing) configuration files can still be used in v4 - https://tailwindcss.com/docs/v4-beta#using-legacy-configuration-files - but it will not be highly configurable through this approach (also note the usage of word "legacy").

## Content Configuration

When creating a `tailwind.config` file, you were required to specify resolvable paths to your source code in the `content` property. This module also did that for you, so it wasn't necessary. However, projects have different natures of organising source code. Moreover, a file may exist in the tracker but not in the app lifecycle/tree; the class utilities from that file would still contribute to the final CSS.

Tailwind v4 now looks at the module graph and detects utilities accordingly. Still, paths can be configured explicitly; read https://tailwindcss.com/docs/v4-beta#configuring-source-detection.

## Exposed CSS variables

There was a little section in Tailwind v3 docs about [referencing (configuration) in JavaScript](https://tailwindcss.com/docs/configuration#referencing-in-java-script). Here again this module provided an `exposeConfig` feature 👼 that would provide tree-shakable, typed values to your configurations.

Tailwind v4 is based on CSS variables now, and the `resolveConfig` function is not exported anymore. https://tailwindcss.com/docs/v4-beta#referencing-theme-values-in-js

---

Given some of the changes pointed above, I'm trying to brainstorm on where we go next. It may be possible to maintain the current usage of the module to work with v4, but it may not enable its best potential. We can also change into a `tailwind.css` based module (have the module generate it and automatically integrate) which seems like a nice idea. We could just be a simple Vite/PostCSS plugin installer too 😄 

So here's what I'm hoping to hear from you:
1. are there current features from the module that you use and heavily rely on? (hooks, exposeConfig, etc)
2. how much configuration do you tend to use for Tailwind, and if you'd move to using the new `@theme`, `@plugin`, etc. directives?
3. is there anything in Tailwind v4 changes that you would want the module to bank on (like no longer providing our own content paths to use automatic detection, and also remove `exposeConfig` to use CSS variables), or possibly still have those abilities (that may not be as-usable at their best potential)?

Let me know what you all think. I'm excited to take this new exciting route that hopefully everyone can enjoy!

**Comment by MickL** [comment]
Personally I "just" want to use Tailwind in my Nuxt project. Since v4 has first class Vite support, I question if a Nuxt module is still needed or what benefits it would have. I was happy when Nuxt Tailwind provided reloading when changing something in the tailwind.config.ts but apparently this is no more needed. I use Nuxt layers but I guess this doesnt affect Tailwind. I only barely use the devtools but if, I never used them for anything Tailwind related.

What is really annoying is that every use of dynamic classes is not catched by Tailwind atm. At the beginning the behavior seemed buggy to me because styles were working and then suddenly not anymore and I couldnt figure out why. After figuring out and understanding the problem the only solution then is to put the classes in the safelist. But I guess there is nothing Nuxt Tailwind could do?

**Comment by hacknug** [comment]
I don't heavily rely on it but being able to use `tw()` (aka `editorSupport`) was really nice.

**Comment by patriktoth67** [comment]
> Personally I "just" want to use Tailwind in my Nuxt project. Since v4 has first class Vite support, I question if a Nuxt module is still needed or what benefits it would have. I was happy when Nuxt Tailwind provided reloading when changing something in the tailwind.config.ts but apparently this is no more needed. I use Nuxt layers but I guess this doesnt affect Tailwind. I only barely use the devtools but if, I never used them for anything Tailwind related.
> 
> What is really annoying is that every use of dynamic classes is not catched by Tailwind atm. At the beginning the behavior seemed buggy to me because styles were working and then suddenly not anymore and I couldnt figure out why. After figuring out and understanding the problem the only solution then is to put the classes in the safelist. But I guess there is nothing Nuxt Tailwind could do?

Same here, "just" want to use Tailwind v4 because of Nuxt UI v3.

**Comment by MickL** [comment]
I tried Nuxt UI 3 with Tailwind 4 a lot already. As far as I see they dont use Nuxt/Tailwind. Works like a charm, I dont know if there is a need for a Nuxt Tailwind module anymore?

**Comment by martinszeltins** [comment]
I came here looking for a way to try out the new Tailwind 4 Beta with Nuxt but it looks like people are saying that there isn't even a real need for a tailwind Nuxt module.

**Comment by ineshbose** [comment]
> I came here looking for a way to try out the new Tailwind 4 Beta with Nuxt but it looks like people are saying that there isn't even a real need for a tailwind Nuxt module.

You can try this out for the time being: https://github.com/pi0/nuxt-tailwindcss4

**Comment by ineshbose** [comment]
So let me do mention, in case I didn't, I'm open to the idea of not taking the module forward.

With that said, there are still minor DX improvements we can provide on top of Tailwind v4. The bare minimum I would think is:
1. Install Vite or PostCSS plugin automatically
2. Auto-add generated CSS template to `nuxt.options.css` (based on layers, etc), or auto detect if `assets/css/tailwind.css` exists and inject that (this is where `@nuxt/ui` or other modules can also build upon, so you don't need to add it yourself).

With the above, you're not having to update *anything* in your `nuxt.config` (except add `@nuxtjs/tailwindcss` to `modules`) - so that's your "just" want to use Tailwind v4. Again, quite a minor benefit, but if it makes a difference to your project (or not) - either way works.

**Comment by MickL** [comment]
No need for any module as I wrote above! If you deploy to Cloudflare just keep in mind Tailwind 4 requires to set build environment to Node 22 atm: https://github.com/tailwindlabs/tailwindcss/issues/15399

**Comment by hacknug** [comment]
> With that said, there are still minor DX improvements we can provide on top of Tailwind v4.

Agreed. There was also no need to use the module before if you configured PostCSS manually so I'm not sure why people feel things have changed so much.

I believe `tw` and the config viewer are reason enough to justify having this module around. Plus being able to just `nuxi module add tailwindcss` and have everything working at once seems like a no brainer for me.

These replies also sound a little like survivorship bias to me. The only people I would expect to comment on a GitHub issue discussing a future version of a module, are the those who are probably comfortable enough to set things up on their own. I'm pretty sure there will be lots of people asking/complaining if there is no module in the future.

**Comment by martinszeltins** [comment]
> I believe `tw` and the config viewer are reason enough to justify having this module around. Plus being able to just `nuxi module add tailwindcss` and have everything working at once seems like a no brainer for me.

I agree, I think Nuxt people are used to installing modules with `nuxi module add tailwind` so this is definitely a big plus.

**Comment by patriktoth67** [comment]
Can anyone help me? I changed my project, installed tailwind v3 configuring PostCSS manually. Then I run `npx @tailwindcss/upgrade@next`  changed to this in nuxt.config.ts:
```ts
    css: ["~/assets/css/main.css"],

    postcss: {
        plugins: {
            "@tailwindcss/postcss": {},
        },
    },
```

And I get this error:
```console
[10:21:30 AM]  ERROR  Cannot restart nuxt:  Package subpath './nesting' is not defined by "exports" in C:\Users\user\Projects\project\livechat-app\frontend\node_modules\tailwindcss\package.json

  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at new NodeError (node:internal/errors:405:5)
  at exportsNotFound (node:internal/modules/esm/resolve:359:10)
  at packageExportsResolve (node:internal/modules/esm/resolve:695:9)
  at resolveExports (node:internal/modules/cjs/loader:567:36)
  at Module._findPath (node:internal/modules/cjs/loader:636:31)
  at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
  at Function.resolve (node:internal/modules/cjs/helpers:116:19)
  at Function._resolve [as resolve] (node_modules\jiti\dist\jiti.js:1:241814)
  at resolveModule (/C:/Users/user/Projects/project/livechat-app/frontend/node_modules/@nuxt/kit/dist/index.mjs:2224:29)
  at requireModule (/C:/Users/user/Projects/project/livechat-app/frontend/node_modules/@nuxt/kit/dist/index.mjs:2229:24)
  at resolveCSSOptions (/C:/Users/user/Projects/project/livechat-app/frontend/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.C2KjQmF9.mjs:1076:22)
  at bundle (/C:/Users/user/Projects/project/livechat-app/frontend/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.C2KjQmF9.mjs:1564:14)
  at async bundle (/C:/Users/user/Projects/project/livechat-app/frontend/node_modules/nuxt/dist/index.mjs:5596:5)
  at async Promise.all (index 1)
  at async build (/C:/Users/user/Projects/project/livechat-app/frontend/node_modules/nuxt/dist/index.mjs:5468:5)
  at async Promise.all (index 1)
  at async NuxtDevServer._load (/C:/Users/user/Projects/project/livechat-app/frontend/node_modules/nuxi/dist/chunks/dev2.mjs:6920:5)
  at async NuxtDevServer.load (/C:/Users/user/Projects/project/livechat-app/frontend/node_modules/nuxi/dist/chunks/dev2.mjs:6810:7)
  at async _applyPromised (/C:/Users/user/Projects/project/livechat-app/frontend/node_modules/nuxi/dist/chunks/dev2.mjs:3804:10)
```

What am I missing or doing wrong?

**Comment by martinszeltins** [comment]
@patriktoth67 I think you don't need postcss anymore

**Comment by patriktoth67** [comment]
Actually nevermind, I found out I cannot even upgrade yet, becouse Nuxt UI pro v3 is not yet finished and we are heavily using it.

**Comment by maxdzin** [comment]
I just tried to use TW v4 without the Nuxt module. I made all the setup things described in the [v4 docs](https://tailwindcss.com/docs/v4-beta#installing-with-vite):
Installed `pnpm add tailwindcss@next @tailwindcss/vite@next`
Added this in `nuxt.config.ts`:
```ts
  css: ['~/assets/styles/main.scss'],

  vite: {
    plugins: [tailwindcss()],
  },
```

Instead of declaring all the theme things in the `css` file, I tried to use `scss`. But TW styling is not working.
Could someone share some advice on how to make it work?
@MickL maybe you tried using scss file also and got successful results with that?

**Comment by martinszeltins** [comment]
> I tried to use `scss`. But TW styling is not working.

Probably should not use `scss` but `css`

**Comment by maxdzin** [comment]
@martinszeltins Yes, that one works.
It is interesting how to go with scss. Digging...

**Comment by MickL** [comment]
No need for scss when using Tailwind. Apply classes like this:

```css
h1 {
   @apply font-bold;
   @apply text-2xl;
}

**Comment by maxdzin** [comment]
@MickL yes, I know that is not necessary. But what if I want to use the powers of scss? That's why I'm trying to make it that way.

**Comment by ineshbose** [comment]
Could this be related?

https://github.com/tailwindlabs/tailwindcss/issues/14376

**Comment by MickL** [comment]
If you use the powers of Tailwind you dont need any scss ever again

**Comment by maxdzin** [comment]
> Could this be related?
> 
> [tailwindlabs/tailwindcss#14376](https://github.com/tailwindlabs/tailwindcss/issues/14376)

@ineshbose It looks like

**Comment by maxdzin** [comment]
>If you use the powers of Tailwind you dont need any scss ever again

Well, it looks like with v4 this may indeed be the case, given the improvements that have been (and will be) made in the new version. Although, of course, there may be some projects and some features that may require other tools (like SCSS).

**Comment by MickL** [comment]
What exactly? I think the whole purpose of Tailwind is not to write css or scss again.

**Comment by maxdzin** [comment]
Hey everyone!
Is dark/light theme switching working for the current v4.0.0-beta.9? Could someone share simple instructions on how to make it work?
Thanks!

**Comment by hacknug** [comment]
> Hey everyone! Is dark/light theme switching working for the current v4.0.0-beta.9? Could someone share simple instructions on how to make it work? Thanks!

This is not the place to ask for this but, according to [the v4 alpha release blog post](https://arc.net/l/quote/hjmdxmei), dark mode is only supported via media queries:

> - Support for other dark modes — right now we only support dark mode using media queries, and still need to reimplement the selector and variant strategies.

Not sure if anything changed in the latest betas as that is the strategy I use in the projects were I tested v4.

**Comment by MickL** [comment]
Thats what I posted already: https://github.com/nuxt-modules/tailwindcss/issues/919#issuecomment-2527798954

**Comment by aparajita** [comment]
@MickL Yes, thank you, that's how I got the first part. Just wanted to add the `tw` bit for completeness.

**Comment by thehouseisonfire** [comment]
New installation guide: https://tailwindcss.com/docs/installation/framework-guides/nuxt

**Comment by MickL** [comment]
Also v4 is out since yesterday :) https://tailwindcss.com/blog/tailwindcss-v4

**Comment by maxdzin** [comment]
Yes! Today I tried migrating one of my Nuxt projects to TW v4, and everything went great. There are still some new things that I haven't tried yet and need to learn, but the first impressions are very good.
And, yes, seems the TW module is no longer needed, at least for me because I'm not using the viewer.

**Comment by McSundae** [comment]
v4 is now official and I finally tried implanting it without this module, I actually hadn't any problems. The migration tool helps alot when you want to update from js config file to the css approach so there is probably no real need anylonger.

**Comment by rylanharper** [comment]
No, tailwind v4 definitely isn't fully compatible with Nuxt just yet.. It seems any `@apply` rule added to a `style` block breaks a component. Obviously tailwind styles go in the template, but in complex apps its often seen to use `:deep` styles in conjunction with the `@apply` rule for embedded richtext from a CMS or data from ecom platforms such as Shopify.

If anyone has found a solution to this let me know, but as of right now it isn't fully compatible with Nuxt just yet. I genuinely don't know if this a Nuxt issue or a tailwind issue.

**Comment by rylanharper** [comment]
^ Update.. I'm an idiot. Apparently there is a new opt in feature that you have to import `@reference "tailwindcss"` to use the `@apply` rule.. Which is certainly a choice lol 😆

**Comment by MickL** [comment]
If you guys use `@nuxt/fonts`, dont forget to set `processCSSVariables` to `true` as [written in the docs](https://fonts.nuxt.com/get-started/configuration#experimental)

Also linking #820 which is kinda a duplicate

**Comment by McSundae** [comment]
Some days later I have to say that there are actually some difficulties that are probably best solved with a module so you dont miss all the small things :D

**Comment by MickL** [comment]
Could you elaborate? I work with Tailwind 4 for some time now and it works like a charm, couldnt be more happy! No need to a Nuxt module from my side but maybe I am missing something?

**Comment by McSundae** [comment]
For example space-y-* seems not to work any longer in vite based installations (which is true for nuxt). See also:
https://github.com/tailwindlabs/tailwindcss/issues/15278

**Comment by MickL** [comment]
But this would rather be something Tailwind needs to fix because it affects all Vite projects which might be most of the projects that use Tailwind. I dont think it is something Nuxt should try to fix for themselves.

**Comment by McSundae** [comment]
@MickL: I guess tailwind will fix this, but I don't know. I would say we have an eye on the tailwind v4 situation for some weeks and especially the next updates.

**Comment by svk-man** [comment]
I get the following error when trying to build solution: "Nuxt Build Error: [vite:css] [postcss] ./assets/css/main.css:1566:20: Unknown word file: ./assets/css/main.css:1566:19"

```
"nuxt": "^3.14.159"
"tailwindcss": "^4.0.0",
"@tailwindcss/vite": "^4.0.6",
```

Tutorial: https://tailwindcss.com/docs/installation/framework-guides/nuxt

**Comment by martinszeltins** [comment]
> I get the following error when trying to build solution: "Nuxt Build Error: [vite:css] [postcss] ./assets/css/main.css:1566:20: Unknown word file: ./assets/css/main.css:1566:19"
> 
> ```
> "nuxt": "^3.14.159"
> "tailwindcss": "^4.0.0",
> "@tailwindcss/vite": "^4.0.6",
> ```
> 
> Tutorial: [tailwindcss.com/docs/installation/framework-guides/nuxt](https://tailwindcss.com/docs/installation/framework-guides/nuxt)

Remove postcss and use the new tailwind Vite plugin

**Comment by svk-man** [comment]
> > I get the following error when trying to build solution: "Nuxt Build Error: [vite:css] [postcss] ./assets/css/main.css:1566:20: Unknown word file: ./assets/css/main.css:1566:19"
> > ```
> > "nuxt": "^3.14.159"
> > "tailwindcss": "^4.0.0",
> > "@tailwindcss/vite": "^4.0.6",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Tutorial: [tailwindcss.com/docs/installation/framework-guides/nuxt](https://tailwindcss.com/docs/installation/framework-guides/nuxt)
> 
> Remove postcss and use the new tailwind Vite plugin

I was hasty, I didn't have postcss installed. The same error still occurs :(

**Comment by martinszeltins** [comment]
@svk-man That's interesting. Then where is this coming from? 🤔 

> Nuxt Build Error: [vite:css] [postcss]

**Comment by MickL** [comment]
So I found one case that could be a reason for Nuxt Tailwind v4 module:
Nuxt layers are not used as [source files](https://tailwindcss.com/docs/detecting-classes-in-source-files) and therefor styles are missing.

What I do atm is adding the source in my main.css:
```css
@import "tailwindcss";
@source "../../../../../packages/shared";
```

It would be cool if they are automatically detected. Especially in Monorepos, e.g. I am using Turbo Repo.

**Comment by skoenfaelt** [comment]
> So I found one case that could be a reason for Nuxt Tailwind v4 module: Nuxt layers are not used as [source files](https://tailwindcss.com/docs/detecting-classes-in-source-files) and therefor styles are missing.
> 
> What I do atm is adding the source in my main.css:
> 
> @import "tailwindcss";
> @source "../../../../../packages/shared";
> It would be cool if they are automatically detected. Especially in Monorepos, e.g. I am using [Turbo Repo](https://turbo.build/repo/docs).

This is because they made a breaking change in v4.0.8 or 4.0.9 

Till now, I can not get it to work with remote layers, in a monorepo. Even with the [newest workaround](https://github.com/tailwindlabs/tailwindcss/issues/16733#issuecomment-2692394603) I can not get it to work. It just does not recognize any tailwind classes.


References: https://github.com/tailwindlabs/tailwindcss/issues/16733

**Comment by alexcroox** [comment]
If this module is looking for DX improvements vs just installing manually finding a way to auto inject:

`@reference "tailwindcss"` into SFC style sections so you don't have to declare it every time you want to use @apply rules would be good.

**Comment by jawa-the-hutt** [comment]
I would second @skoenfaelt comment above.  I've had to version pin to Tailwind `4.0.7` in my monorepo with layers to get the tailwind styles to come back.  

I started with a brand new project with Nuxt UI 3 that uses Tailwind 4 so I don't even have this module installed.  Things worked fine before adding the layers into the mix but afterwards I struggled for a couple of days trying to figure out why everything broke in the UI from a styling standpoint.  Finally found this issue and then the subsequent referenced in the Tailwind repo.

**Comment by khawarizmus** [comment]
What's the verdict? should i wait for the module to support v4 or i just set it up manually? I already use this module but i want to upgrade to v4.

**Comment by florian-strasser** [comment]
@khawarizmus If you want to upgrade to v4 you should setup Tailwind manually. 

Here is the guide from tailwind:
[https://tailwindcss.com/docs/installation/framework-guides/nuxt](https://tailwindcss.com/docs/installation/framework-guides/nuxt)

**Comment by MickL** [comment]
What is the benifit exactly?

**Comment by ineshbose** [comment]
> What is the benifit exactly? 

I think its clear you're not keen in installing a module, and I respect that, but as hacknug's point above (along with several others) - they're proposing DX improvements and room for a module, and I'm sincerely looking to provide anything that can help with those requirements. It's not helpful to be lurking in this thread discouraging the development of a next version if it's your POV 😄

**Comment by ineshbose** [comment]
> Hey! Actually I mentioned a valid point why a module would make sense. Therefor my question, what is the benifit of @pi0  module, was geuine and I am still interested what is the benifit of his module over manual installing? For example if it would provide Nuxt Layers support, I would want to install and use it too. But if it has no advantage over manually installing, it wouldnt make sense for me at least. Also my question comes up because 1. it is flagged experimental and 2. I know he made it long before Tailwind 4 came out. So maybe it is already out of date? Or maybe it is actually very useful? 

Ok, I understand. Perhaps it would help to refresh through the issue thread. As this mentioned in the description along with the points raised in the thread, the main agenda is finding benefits of the module. First, auto-installation of the plugin and setting up CSS file - and I have mentioned repeatedly that this is a minor benefit and some may not see the worth. Second, you mention layers, esp after TW v4.0.8 and that's somewhere where we can try to develop a solution. Third, utils like `tw` and/or viewer (depending if we get TW4 support there or something else). Again, that is the point of this issue thread @MickL 

Now the repo is under Pooya's account and was set up before stable release but I was provided access to continue development therefore changes there are quite likely to be the ones I migrate into the `@nuxtjs` module, so if there are issues on that end, then I'm looking for feedback. Hope that helps.

**Comment by Eazash** [comment]
For me, a huge benefit of this package was that it exposes the tailwind config. If I had to pass specifc colors or styles to a library/package that has to be instantiated during runtime, having access to the config in JS land was great.  I would not like to see that API go away

**Comment by MickL** [comment]
Not sure if this is still possible with Tailwind 4 because now there is no more js/ts file, instead everything is based on a css file and css variables.

**Comment by Eazash** [comment]
Tailwind v4 docs does mention using [getComputedStyle](https://tailwindcss.com/docs/theme#referencing-in-javascript) but that needs using the document root and wouldn't work in SSR environments

**Comment by gkatsanos** [comment]
so basically the main doc page instructions lead you to a broken install, correct?

**Comment by Psycarlo** [comment]
> Hey guys, at the moment I'll recommend setting up
> 
> https://github.com/pi0/nuxt-tailwindcss4
> 
> It should just be a drop in replacement for when this module supports v4 (and I am aiming by April)!

Does it work with layers?

**Comment by ineshbose** [comment]
> > Hey guys, at the moment I'll recommend setting up
> > https://github.com/pi0/nuxt-tailwindcss4
> > It should just be a drop in replacement for when this module supports v4 (and I am aiming by April)!
> 
> Does it work with layers?

Not with first-class support yet. Good news is, The final minor version of `@nuxtjs/tailwindcss@v6` is out now, and from this point I shall be focusing development on v7, with layers as focus too. 🙂

**Comment by Psycarlo** [comment]
@ineshbose is v7 the version that will have full tw v4 support?

**Comment by ineshbose** [comment]
> @ineshbose is v7 the version that will have full tw v4 support?

Yes

**Comment by Eronne** [comment]
Glad to hear that this module will support tailwindcss v4 & Nuxt layer! 😍
Been struggling with that for 3 days

**Comment by Psycarlo** [comment]
@ineshbose Could you provide an estimated release date for version 7?

**Comment by DGINXREAL** [comment]
@ineshbose please release

**Comment by ineshbose** [comment]
Thanks for the nudge guys - just made a beta release now. I don't think I'd target more than 2 more beta releases until stable. Please feel free to use and feedback the module.

**Comment by ineshbose** [comment]
Hi all, just checking in if I could get some feedback on the beta so far? I am yet to triage some open issues, but I'm not seeing many of them either way!

**Comment by ineshbose** [comment]
I should reopen this for the moment to collect feedback and visibility over the beta version for now 🙂

**Comment by Psycarlo** [comment]
@ineshbose I am getting some trouble setting up `@nuxtjs/tailwindcss` + `shadcn-vue` in a nuxt layer.

Structure:
-- apps
---- www (extends ui package)
-- packages
---- ui (@nuxtjs/tailwindcss + shadcn-vue)

By adding `ui/app/assets/css/tailwind.css` (https://www.shadcn-vue.com/docs/installation/nuxt.html), looks like the styles are not exported.

**Comment by danielwaltz** [comment]
Tried out the beta version of the module in an existing Nuxt project that was set up to use the Vite plugin directly. After removing the Vite plugin and adding the module, everything was working as I would expect still! This include customized tailwind using plugins like DaisyUI and Typography. Looking forward to it going stable!

**Comment by Psycarlo** [comment]
@hacknug The playground does not show what I am looking for.

**Comment by Bobakanoosh** [comment]
Having HMR issues with Nuxt layers + Tailwind V4
https://github.com/nuxt/nuxt/issues/33267

**Comment by ineshbose** [comment]
> For new nuxt 4 projects I would not need a nuxt/tailwind module. What I need is a easy way to connect the main tailwind.css with those from my remote layers in node_modules. [@source](https://github.com/source) is so what a no go. Tailwind/vite 4.0.7 discovers it automatically, tailwind/vite 4.0.8 destroys that.
> 
> So do I need a module? Mainly no, if the main goal of the module is to easily handle discovering remote tailwind.css files. I would change my mind.
> 
> The tailwind viewer should also view those layers.
> 
> For everything else I just can use official tailwind installation guide.

So my solution for that has been `sources.css` that acts as an aggregator of all layers here:
https://github.com/nuxt-modules/tailwindcss/blob/b04744fa9d4175927d810c25c97a14a20c009a3b/src/import-css.ts#L75C23-L75C45

I haven't been able to test and collect feedback too much, but if anyone has a better idea I would promptly review that PR 🙂

**Comment by davestewart** [comment]
It's the second time I've installed the module for Nuxt 4 and Nuxt UI 3, got a page of unstyled HTML, then installed the module, found it didn't help, read through the posts, took out the module and just added this to my nuxt config, and it worked:

```js
// nuxt.config.ts
{
  css: ['~/assets/css/main.css'], // all that is needed for Nuxt 4, Nuxt UI 3 and Tailwind 4
}
```

I'm not sure if or where this should be documented, but it would be nice if (even in this module) if there was a canonical "this is what to configure if you are using this or that or the other".

I have an "integrations" doc for my library Alias HQ and I make sure I am exhaustive on what integration a user needs, and how they should configure the lib:

- https://github.com/davestewart/alias-hq/blob/main/docs/integrations.md
